server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
