server:
  port: 8085
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
